#!/bin/bash
TEMPLATECONF=$(pwd)/conf
git clone -b dunfell git://git.yoctoproject.org/poky.git
cd poky
git clone -b dunfell git://git.yoctoproject.org/meta-raspberrypi
. oe-init-build-env build
#cp ../../conf/local.conf conf/
#cp ../../conf/bblayers.conf conf/
#bitbake rpi-basic-image
bitbake core-image-base
